#!/usr/bin/expect
#
# create in 2017/08/27, by lalawue


set timeout 5
if { $argc != 3 } {
    send_user "$argv0 [USER@IP:DIR] [PASSWD] [LOCAL_DIR]"
    exit
}

set user_ip_dir [lrange $argv 0 0]
set pass_word   [lrange $argv 1 1]

set local_dir   [lrange $argv 2 2]


proc do_send_password { pass_word } {
    send $pass_word\r
    expect "total size"    
}

# login server and run rsync
spawn rsync -arvz --delete $local_dir $user_ip_dir
expect {
    "password:" {
        do_send_password $pass_word
    }
    "Password for *" {
        do_send_password $pass_word
    }
}

